### get all
GET http://localhost:5000/book

### get single
GET  http://localhost:5000/book/6648a161f3d1758418f4c167

### get add contact
Post http://localhost:5000/book
Content-Type: application/json

{
    "name":"Dipesh45",
    "email":"fakhir@gmail.com",
    "phone":"599"
}

### get Update
Put http://localhost:5000/book/66495201324f8c9084aa6eca
Content-Type: application/json

{
    "name": "Dipesh45qwe yyyyy   y",
    "email": "fakhir@gmail.com",
    "phone": "599",
    "createdAt": "2024-05-19T01:08:32.678Z",
    "updatedAt": "2024-05-19T01:08:32.678Z",
    "__v": 0
}


### get delete
delete http://localhost:5000/book/66495201324f8c9084aa6eca


### get add register
Post http://localhost:5000/user/register
Content-Type: application/json

{
    "userName" : "fakhir",
    "email": "hmfakhirisrar2@gmail.com",
    "password":"123"
}

### get add Login
Post http://localhost:5000/user/login
Content-Type: :application/json

{
    "email":"hmfakhirisrar2@gmail.com",
    "password":"123"
}

### get add current
GET http://localhost:5000/user/current

